#!/usr/bin/env bash
#
# Build MARP decks to HTML + PDF for the Hugo site.
#
#   ./build-slides.sh                     # build every deck
#   ./build-slides.sh lecture-01-welcome  # build one deck
#
# Sources live in slides/ — deliberately outside content/, so Hugo never tries
# to render a deck as a regular page. Output goes to static/slides/, which Hugo
# copies verbatim into public/ at build time.
#
# CI runs this before `hugo`, so pushing a .md is enough to update the site.
# Locally it is for previewing; static/slides/ is gitignored.

set -euo pipefail

SRC_DIR="./slides"
OUT_DIR="./static/slides"
THEME_FILE="${SRC_DIR}/_theme.css"
DATA_FILE="./data/slides.yaml"

# Pinned so CI and local builds render identically.
MARP=(npx --yes @marp-team/marp-cli@4.5.0)

# --theme            apply our CSS. NOTE: there is no --css flag; marp-cli
#                    silently ignores unknown options, so --css meant the theme
#                    was never applied at all.
# --html             allow raw HTML in markdown (the .columns / .emphasize divs)
# --allow-local-files let the headless browser read ./images/* when rendering
#                    PDFs. Without it images are silently dropped from the PDF.
MARP_FLAGS=(--theme "$THEME_FILE" --html --allow-local-files)

# Read a single top-level field out of a markdown file's YAML frontmatter.
frontmatter_field() {
  local file="$1" field="$2"
  awk -v field="$field" '
    NR == 1 && /^---[[:space:]]*$/ { in_fm = 1; next }
    in_fm && /^---[[:space:]]*$/   { exit }
    in_fm && index($0, field ":") == 1 {
      val = substr($0, length(field) + 2)
      sub(/^[[:space:]]+/, "", val)
      sub(/[[:space:]]+$/, "", val)
      gsub(/^"|"$/, "", val)
      gsub(/^'\''|'\''$/, "", val)
      print val
      exit
    }
  ' "$file"
}

yaml_escape() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

if [ ! -f "$THEME_FILE" ]; then
  echo "Error: theme not found at $THEME_FILE" >&2
  exit 1
fi

mkdir -p "$OUT_DIR" "$(dirname "$DATA_FILE")"

# Which decks to build this run.
if [ $# -gt 0 ]; then
  targets=("${SRC_DIR}/${1%.md}.md")
  if [ ! -f "${targets[0]}" ]; then
    echo "Error: ${targets[0]} not found" >&2
    exit 1
  fi
else
  targets=()
  for f in "$SRC_DIR"/lecture-*.md; do
    [ -e "$f" ] || continue
    targets+=("$f")
  done
  if [ ${#targets[@]} -eq 0 ]; then
    echo "Error: no lecture-*.md files in $SRC_DIR" >&2
    exit 1
  fi
fi

# HTML output keeps image srcs relative (src="./images/foo.png"), so the images
# have to sit next to the generated HTML. PDFs embed them at build time.
if [ -d "${SRC_DIR}/images" ]; then
  echo "Copying images..."
  mkdir -p "${OUT_DIR}/images"
  cp -R "${SRC_DIR}/images/." "${OUT_DIR}/images/"
fi

echo "Building MARP slides..."
for slide_file in "${targets[@]}"; do
  slug=$(basename "$slide_file" .md)
  echo "  → ${slug}"

  "${MARP[@]}" "$slide_file" "${MARP_FLAGS[@]}" \
    --output "${OUT_DIR}/${slug}.html"

  "${MARP[@]}" "$slide_file" "${MARP_FLAGS[@]}" --pdf --pdf-outlines \
    --output "${OUT_DIR}/${slug}.pdf"
done

# Always regenerate the index over *every* deck, even on a single-deck build,
# so the site's /slides/ listing never goes stale.
echo "Writing ${DATA_FILE}..."
{
  echo "# Generated by build-slides.sh — do not edit by hand."
  echo "decks:"
  for f in "$SRC_DIR"/lecture-*.md; do
    [ -e "$f" ] || continue
    slug=$(basename "$f" .md)
    title=$(frontmatter_field "$f" title)
    date=$(frontmatter_field "$f" date)
    description=$(frontmatter_field "$f" description)
    echo "  - slug: \"$(yaml_escape "$slug")\""
    echo "    title: \"$(yaml_escape "${title:-$slug}")\""
    echo "    date: \"$(yaml_escape "$date")\""
    echo "    description: \"$(yaml_escape "$description")\""
  done
} > "$DATA_FILE"

echo
echo "✓ Built ${#targets[@]} deck(s) into ${OUT_DIR}"
echo "  HTML → served at /slides/<slug>.html (presenter view: press 'p')"
echo "  PDF  → served at /slides/<slug>.pdf, and what you upload to D2L"
