baseURL: "https://msu-cerl.github.io/cmse101/"
languageCode: "en-us"
title: "CMSE 101: Introduction to Machine Learning and Society"
theme: "terminal"

caches:
  images:
    dir: :cacheDir/images

params:
  # Hide metadata elements
  showReadingTime: false
  showWordCount: false
  showLastMod: false
  showDate: false
  showAuthor: false
  showTags: false
  showCategories: false

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 10
    - name: "Learning Goals"
      url: "/learning-goals/"
      weight: 20
    - name: "Schedule"
      url: "/schedule/"
      weight: 30
    # - name: "Assignments"
    #   url: "/assignments/"
    #   weight: 40
    - name: "Resources"
      url: "/resources/"
      weight: 50
    # - name: "Contact"
    #   url: "/contact/"
    #   weight: 60